apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-auth
namePrefix: dev-
resources:
  - namespace.yaml
  - ../../base
configMapGenerator:
  - name: logto-config
    behavior: merge
    envs:
      - configmap.properties

patches:
  - target:
      kind: Deployment
      name: logto
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: logto
      spec:
        template:
          spec:
            hostAliases:
              - ip: "PLACEHOLDER_IP_1"
                hostnames:
                  - "PLACEHOLDER_AUTH_DOMAIN"
                  - "PLACEHOLDER_ADMIN_DOMAIN"
              - ip: "PLACEHOLDER_IP_2"
                hostnames:
                  - "PLACEHOLDER_AUTH_DOMAIN"
                  - "PLACEHOLDER_ADMIN_DOMAIN"
