apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - namespace.yaml
  - ../../base
configMapGenerator:
  - name: logto-config
    behavior: merge
    envs:
      - configmap.properties
